import json

OO = (0,0,0)
CC = (255,255,255)

letters = {
    "9":[[OO,OO,OO,OO,OO],
         [OO,CC,CC,CC,OO],
         [CC,OO,OO,OO,CC],
         [CC,OO,OO,OO,CC],
         [OO,CC,CC,CC,CC],
         [OO,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,CC,CC,OO]
		 ],
    "8":[[OO,OO,OO,OO,OO],
         [OO,CC,CC,CC,OO],
         [CC,OO,OO,OO,CC],
         [CC,OO,OO,OO,CC],
         [OO,CC,CC,CC,OO],
         [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,CC,CC,OO]
		 ],
    "7":[[OO,OO,OO,OO,OO],
         [OO,CC,CC,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO]
		 ],
    "6":[[OO,OO,OO,OO,OO],
         [OO,CC,CC,CC,OO],
         [CC,OO,OO,OO,OO],
         [CC,CC,CC,OO,OO],
         [CC,OO,OO,CC,OO],
         [CC,OO,OO,CC,OO],
		 [CC,OO,OO,CC,OO],
		 [OO,CC,CC,OO,OO]
		 ],
    "5":[[OO,OO,OO,OO,OO],
         [CC,CC,CC,CC,CC],
         [CC,OO,OO,OO,OO],
         [CC,OO,OO,OO,OO],
         [OO,CC,CC,CC,OO],
         [OO,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,CC,CC,OO]
		 ],
    "4":[[OO,OO,OO,OO,OO,OO],
         [OO,OO,OO,CC,OO,OO],
         [OO,OO,CC,CC,OO,OO],
         [OO,OO,CC,CC,OO,OO],
         [OO,CC,OO,CC,OO,OO],
         [OO,CC,OO,CC,OO,OO],
		 [CC,CC,CC,CC,CC,CC],
		 [OO,OO,OO,CC,OO,OO]
		 ],
    "3" :[[OO,OO,OO,OO,OO],
         [OO,CC,CC,OO,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,CC,CC,OO,OO],
         [OO,OO,OO,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,CC,CC,OO,OO]
		 ],
    "2" :[[OO,OO,OO,OO,OO],
         [OO,CC,CC,CC,OO],
         [CC,OO,OO,OO,CC],
         [CC,OO,OO,CC,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,CC,OO,OO,OO],
         [CC,CC,CC,CC,CC],
		 ],
    "1" :[[OO,OO,CC,OO,OO],
         [OO,CC,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,CC,CC,OO]
		 ],
    "0" :[[OO,OO,OO,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,CC,OO,CC,OO],
         [CC,OO,OO,OO,CC],
         [CC,OO,CC,OO,CC],
         [CC,OO,OO,OO,CC],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "|" :[[OO,OO,OO],
         [OO,CC,OO],
         [OO,CC,OO],
         [OO,CC,OO],
         [OO,CC,OO],
         [OO,CC,OO],
		 [OO,CC,OO],
		 [OO,CC,OO]
		 ],
    "\\" :[[OO,CC,OO,OO,OO,OO],
         [OO,CC,OO,OO,OO,OO],
         [OO,OO,CC,OO,OO,OO],
         [OO,OO,CC,OO,OO,OO],
         [OO,OO,OO,CC,OO,OO],
         [OO,OO,OO,CC,OO,OO],
		 [OO,OO,OO,OO,CC,OO],
		 [OO,OO,OO,OO,CC,OO]
		 ],
    "?":[[OO,OO,OO,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,CC,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "/" :[[OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO]
		 ],
    "," :[[OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
		 [OO,CC,OO],
		 [CC,OO,OO]
		 ],
    "." :[[OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
		 [OO,CC,OO],
		 [OO,OO,OO]
		 ],
    ">" :[[OO,OO,OO,OO],
         [CC,OO,OO,OO],
         [OO,CC,OO,OO],
         [OO,OO,CC,OO],
         [OO,OO,OO,CC],
         [OO,OO,CC,OO],
		 [OO,CC,OO,OO],
		 [CC,OO,OO,OO]
		 ],
	"<" :[[OO,OO,OO,OO],
         [OO,OO,OO,CC],
         [OO,OO,CC,OO],
         [OO,CC,OO,OO],
         [CC,OO,OO,OO],
         [OO,CC,OO,OO],
		 [OO,OO,CC,OO],
		 [OO,OO,OO,CC]
		 ],
    "#" :[[OO,CC,OO,CC,OO],
         [OO,CC,OO,CC,OO],
         [CC,CC,CC,CC,CC],
         [OO,CC,OO,CC,OO],
         [OO,CC,OO,CC,OO],
         [CC,CC,CC,CC,CC],
         [OO,CC,OO,CC,OO],
         [OO,CC,OO,CC,OO],
		 ],
    "~" :[[OO,OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO,OO],
         [OO,CC,CC,OO,OO,CC],
         [CC,OO,CC,CC,OO,OO],
         [OO,OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO,OO]
		 ],
         " " :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    "@" :[[OO,OO,OO,OO,OO],
         [OO,CC,CC,CC,OO],
         [CC,OO,OO,OO,CC],
         [CC,OO,CC,OO,CC],
         [CC,OO,CC,OO,CC],
         [CC,OO,CC,CC,CC],
		 [CC,OO,OO,OO,OO],
		 [OO,CC,CC,CC,CC]
		 ],
    "'" :[[OO,CC,OO],
         [OO,CC,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
		 [OO,OO,OO],
		 [OO,OO,OO]
		 ],
    ";" :[[OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,CC,OO],
         [OO,OO,OO],
         [OO,CC,OO],
		 [OO,CC,OO],
		 [CC,OO,OO]
		 ],
    ":" :[[OO,OO,OO],
         [OO,OO,OO],
         [OO,OO,OO],
         [OO,CC,OO],
         [OO,OO,OO],
         [OO,OO,OO],
		 [CC,OO,OO],
		 [OO,OO,OO]
		 ],
    "}" :[[OO,OO,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,CC,OO],
         [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,OO,OO]
		 ],
    "{" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,CC,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
		 [OO,OO,OO,CC,OO]
		 ],
    "]" :[[OO,CC,CC,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,CC,CC,CC,OO]
		 ],
    "[" :[[OO,CC,CC,CC,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,CC,CC,OO]
		 ],
    "+" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [CC,CC,CC,CC,CC],
         [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    "=" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [CC,CC,CC,CC,CC],
         [OO,OO,OO,OO,OO],
         [CC,CC,CC,CC,CC],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    "_" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [CC,CC,CC,CC,CC]
		 ],
    "-" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,CC,CC,CC,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    ")" :[[OO,CC,OO,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,OO,CC,OO],
         [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,OO,OO]
		 ],
    "(" :[[OO,OO,OO,CC,OO],
         [OO,OO,CC,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,OO,CC,OO]
		 ],
    "*" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    "&" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
	"^" :[[OO,OO,CC,OO,OO],
         [OO,CC,OO,CC,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    "%" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [CC,CC,OO,OO,CC],
         [CC,CC,OO,CC,OO],
         [OO,OO,CC,OO,OO],
		 [OO,CC,OO,CC,CC],
		 [CC,OO,OO,CC,CC]
		 ],
         
    "$" :[[OO,OO,OO,OO,OO],
         [OO,OO,CC,OO,OO],
         [OO,CC,CC,CC,CC],
         [CC,OO,CC,OO,OO],
         [OO,CC,CC,CC,OO],
         [OO,OO,CC,OO,CC],
         [OO,CC,CC,CC,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "£" :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,CC,CC],
         [OO,OO,CC,OO,OO],
         [OO,CC,OO,OO,OO],
         [CC,CC,CC,CC,CC],
         [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [CC,CC,CC,CC,CC]
		 ],
    "\"" :[[OO,OO,OO,OO,OO],
         [OO,CC,OO,CC,OO],
         [OO,CC,OO,CC,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    "!" :[[OO,OO,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
         [OO,CC,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,OO,OO]
		 ],
	" " :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    "W" :[[OO,OO,OO,OO,OO],
         [CC,OO,OO,OO,CC],
         [CC,OO,OO,OO,CC],
         [CC,OO,OO,OO,CC],
         [CC,OO,CC,OO,CC],
         [CC,OO,CC,OO,CC],
		 [CC,CC,OO,CC,CC],
		 [CC,OO,OO,OO,CC]
		 ],
    "w" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,CC,OO,CC],
		 [CC,CC,OO,CC,CC],
		 [CC,OO,OO,OO,CC]
		 ],
    "Q" :[[OO,OO,CC,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,OO,CC,CC]
		 ],
    "q" :[[OO,CC,CC,CC,CC,OO,OO],
		 [CC,OO,OO,OO,CC,OO,OO],
		 [CC,OO,OO,OO,CC,OO,OO],
		 [OO,CC,OO,OO,CC,OO,OO],
		 [OO,OO,CC,CC,CC,OO,OO],
		 [OO,OO,OO,OO,CC,OO,OO],
		 [OO,OO,OO,OO,CC,CC,OO],
		 [OO,OO,OO,OO,CC,OO,OO]
		 ],
    "E" :[[OO,OO,OO,OO,OO],
		 [CC,CC,CC,CC,CC],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,CC,CC,CC,CC],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,CC,CC,CC,CC]
		 ],
    "e" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,OO,CC,CC,OO]
		 ],
    "R" :[[CC,CC,CC,CC,OO],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,CC,CC,CC,CC],
		 [CC,CC,OO,OO,OO],
		 [CC,OO,CC,OO,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,OO,OO,CC]
		 ],
    "r" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [CC,CC,CC,OO,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO]
		 ],
    "T" :[[CC,CC,CC,CC,CC],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "t" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [CC,CC,CC,CC,CC],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,CC,OO]
		 ],
    "Y" :[[CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "y" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [CC,CC,OO,OO,OO]
		 ],
    "U" :[[CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,CC,OO,CC,CC],
		 [OO,CC,CC,CC,OO]
		 ],
    "u" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "I" :[[CC,CC,CC,CC,CC],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [CC,CC,CC,CC,CC]
		 ],
    "i" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "O" :[[OO,CC,CC,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,CC,CC,OO]
		 ],
    "o" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "P" :[[CC,CC,CC,OO,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,CC,CC,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO]
		 ],
    "p" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [CC,CC,OO,OO,OO],
		 [CC,OO,CC,OO,OO],
		 [CC,CC,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO]
		 ],
    "A" :[[OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [CC,CC,CC,CC,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC]
		 ],
    "a" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,CC,CC,OO]
		 ],
    "S" :[[CC,CC,CC,CC,CC],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,CC,CC,CC,CC],
		 [OO,OO,OO,OO,CC],
		 [OO,OO,OO,OO,CC],
		 [OO,OO,OO,OO,CC],
		 [CC,CC,CC,CC,CC]
		 ],
    "s" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,CC,CC,CC,OO]
		 ],
    "D" :[[CC,CC,CC,OO,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,CC,OO],
		 [CC,CC,CC,OO,OO]
		 ],
    "d" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,CC,CC,OO]
		 ],
    "F" :[[CC,CC,CC,CC,CC],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,CC,CC,CC,CC],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO]
		 ],
    "f" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,CC,CC],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,CC,CC],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "G" :[[OO,CC,CC,CC,CC],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,CC,CC,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,CC,CC,OO]
		 ],
    "g" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,CC,CC,OO,OO]
		 ],
    "H" :[[CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,CC,CC,CC,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC]
		 ],
    "h" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,CC,OO,CC,OO]
		 ],
    "J" :[[CC,CC,CC,CC,CC],
		 [OO,OO,OO,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [CC,OO,OO,CC,OO],
		 [OO,CC,CC,OO,OO]
		 ],
    "j" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "K" :[[CC,OO,OO,OO,CC],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,CC,OO,OO],
		 [CC,CC,OO,OO,OO],
		 [CC,OO,CC,OO,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC]
		 ],
    "k" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,CC,OO,OO],
		 [OO,CC,OO,CC,OO]
		 ],
    "L" :[[CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,CC,CC,CC,CC]
		 ],
    "l" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "Z" :[[CC,CC,CC,CC,CC],
		 [OO,OO,OO,CC,OO],
		 [OO,OO,OO,CC,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [CC,CC,CC,CC,CC]
		 ],
    "z" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,CC,CC,OO]
		 ],
    "X" :[[CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC]
		 ],
    "x" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,CC,OO,CC,OO]
		 ],
    "C" :[[OO,OO,CC,CC,CC],
		 [OO,CC,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [CC,OO,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,OO,CC,CC,CC]
		 ],
    "c" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,CC,CC,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,OO,CC,CC,OO]
		 ],
    "V" :[[CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "v" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,OO,CC,OO,OO]
		 ],
    "B" :[[CC,CC,CC,OO,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,CC,CC,OO,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,OO,OO,CC,OO],
		 [CC,CC,CC,CC,OO]
		 ],
    "b" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,OO,OO,OO],
		 [OO,CC,CC,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,CC,OO,OO]
		 ],
    "N" :[[CC,OO,OO,OO,CC],
		 [CC,CC,OO,OO,CC],
		 [CC,CC,OO,OO,CC],
		 [CC,CC,OO,OO,CC],
		 [CC,OO,CC,OO,CC],
		 [CC,OO,CC,OO,CC],
		 [CC,OO,OO,CC,CC],
		 [CC,OO,OO,CC,CC]
		 ],
    "n" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,CC,CC,OO],
		 [OO,CC,OO,CC,OO],
		 [OO,CC,OO,CC,OO]
		 ],
    "M" :[[CC,OO,OO,OO,CC],
		 [CC,CC,OO,CC,CC],
		 [CC,OO,CC,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC],
		 [CC,OO,OO,OO,CC]
		 ],
    "m" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,CC,OO,CC,OO],
		 [CC,OO,CC,OO,CC],
		 [CC,OO,CC,OO,CC],
		 [CC,OO,CC,OO,CC]
		 ]}

with open("letters.json", "w") as jason_file:
    #jason_file.write(json.dump(letters, letters.json))
    json.dump(letters, jason_file)

def writing(file_name, text):
    with open(file_name, "w") as file_name:
        file_name.write(str(text))
        return(file_name.read)
"""    
letters = {
    " " :[[OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
         [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO]
		 ],
    "W" :[[OO,OO,OO,OO,OO],
         [FC,OO,OO,OO,FC],
         [FC,OO,OO,OO,FC],
         [FC,OO,OO,OO,FC],
         [FC,OO,FC,OO,FC],
         [FC,OO,FC,OO,FC],
		 [FC,FC,OO,FC,FC],
		 [FC,OO,OO,OO,FC]
		 ],
    "w" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,FC,OO,FC],
		 [FC,FC,OO,FC,FC],
		 [FC,OO,OO,OO,FC]
		 ],
    "Q" :[[OO,OO,FC,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,OO,FC,FC]
		 ],
    "q" :[[OO,FC,FC,FC,FC,OO,OO],
		 [FC,OO,OO,OO,FC,OO,OO],
		 [FC,OO,OO,OO,FC,OO,OO],
		 [OO,FC,OO,OO,FC,OO,OO],
		 [OO,OO,FC,FC,FC,OO,OO],
		 [OO,OO,OO,OO,FC,OO,OO],
		 [OO,OO,OO,OO,FC,FC,OO],
		 [OO,OO,OO,OO,FC,OO,OO]
		 ],
    "E" :[[OO,OO,OO,OO,OO],
		 [FC,FC,FC,FC,FC],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,FC,FC,FC,FC],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,FC,FC,FC,FC]
		 ],
    "e" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,OO,FC,FC,OO]
		 ],
    "R" :[[FC,FC,FC,FC,OO],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,FC,FC,FC,FC],
		 [FC,FC,OO,OO,OO],
		 [FC,OO,FC,OO,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,OO,OO,FC]
		 ],
    "r" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [FC,FC,FC,OO,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO]
		 ],
    "T" :[[FC,FC,FC,FC,FC],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "t" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [FC,FC,FC,FC,FC],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,FC,OO]
		 ],
    "Y" :[[FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "y" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [FC,OO,OO,OO,FC],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [FC,FC,OO,OO,OO]
		 ],
    "U" :[[FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,FC,OO,FC,FC],
		 [OO,FC,FC,FC,OO]
		 ],
    "u" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "I" :[[FC,FC,FC,FC,FC],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [FC,FC,FC,FC,FC]
		 ],
    "i" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "O" :[[OO,FC,FC,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,FC,FC,OO]
		 ],
    "o" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "P" :[[FC,FC,FC,OO,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,FC,FC,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO]
		 ],
    "p" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [FC,FC,OO,OO,OO],
		 [FC,OO,FC,OO,OO],
		 [FC,FC,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO]
		 ],
    "A" :[[OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [FC,FC,FC,FC,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC]
		 ],
    "a" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,FC,FC,OO]
		 ],
    "S" :[[FC,FC,FC,FC,FC],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,FC,FC,FC,FC],
		 [OO,OO,OO,OO,FC],
		 [OO,OO,OO,OO,FC],
		 [OO,OO,OO,OO,FC],
		 [FC,FC,FC,FC,FC]
		 ],
    "s" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,FC,FC,FC,OO]
		 ],
    "D" :[[FC,FC,FC,OO,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,FC,OO],
		 [FC,FC,FC,OO,OO]
		 ],
    "d" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,FC,FC,OO]
		 ],
    "F" :[[FC,FC,FC,FC,FC],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,FC,FC,FC,FC],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO]
		 ],
    "f" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,FC,FC],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,FC,FC],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "G" :[[OO,FC,FC,FC,FC],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,FC,FC,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [OO,FC,FC,FC,OO]
		 ],
    "g" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,FC,FC,OO,OO]
		 ],
    "H" :[[FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,FC,FC,FC,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC]
		 ],
    "h" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,FC,OO,FC,OO]
		 ],
    "J" :[[FC,FC,FC,FC,FC],
		 [OO,OO,OO,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [FC,OO,OO,FC,OO],
		 [OO,FC,FC,OO,OO]
		 ],
    "j" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "K" :[[FC,OO,OO,OO,FC],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,FC,OO,OO],
		 [FC,FC,OO,OO,OO],
		 [FC,OO,FC,OO,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC]
		 ],
    "k" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,FC,OO,OO],
		 [OO,FC,OO,FC,OO]
		 ],
    "L" :[[FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,FC,FC,FC,FC]
		 ],
    "l" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "Z" :[[FC,FC,FC,FC,FC],
		 [OO,OO,OO,FC,OO],
		 [OO,OO,OO,FC,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [FC,FC,FC,FC,FC]
		 ],
    "z" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,FC,FC,FC,OO]
		 ],
    "X" :[[FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC]
		 ],
    "x" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,FC,OO,FC,OO]
		 ],
    "C" :[[OO,OO,FC,FC,FC],
		 [OO,FC,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [FC,OO,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,OO,FC,FC,FC]
		 ],
    "c" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,FC,FC,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,OO,FC,FC,OO]
		 ],
    "V" :[[FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "v" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,OO,FC,OO,OO]
		 ],
    "B" :[[FC,FC,FC,OO,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,FC,FC,OO,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,OO,OO,FC,OO],
		 [FC,FC,FC,FC,OO]
		 ],
    "b" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,OO,OO,OO],
		 [OO,FC,FC,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,FC,OO,OO]
		 ],
    "N" :[[FC,OO,OO,OO,FC],
		 [FC,FC,OO,OO,FC],
		 [FC,FC,OO,OO,FC],
		 [FC,FC,OO,OO,FC],
		 [FC,OO,FC,OO,FC],
		 [FC,OO,FC,OO,FC],
		 [FC,OO,OO,FC,FC],
		 [FC,OO,OO,FC,FC]
		 ],
    "n" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,FC,FC,OO],
		 [OO,FC,OO,FC,OO],
		 [OO,FC,OO,FC,OO]
		 ],
    "M" :[[FC,OO,OO,OO,FC],
		 [FC,FC,OO,FC,FC],
		 [FC,OO,FC,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC],
		 [FC,OO,OO,OO,FC]
		 ],
    "m" :[[OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,OO,OO,OO,OO],
		 [OO,FC,OO,FC,OO],
		 [FC,OO,FC,OO,FC],
		 [FC,OO,FC,OO,FC],
		 [FC,OO,FC,OO,FC]
		 ]}
"""